# Generated by Django 2.2.5 on 2019-10-19 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_auto_20191019_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 2, 56, 44, 428613, tzinfo=utc)),
        ),
    ]
